version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: wallet-carrefour
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root2024Carrefour
      POSTGRES_DB: wallet
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: